"""remove auth_provider

Revision ID: 5791e8caac99
Revises: debb024c59d5
Create Date: 2026-06-25 13:15:29.615738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5791e8caac99'
down_revision: Union[str, Sequence[str], None] = 'debb024c59d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
